# Generated by Django 5.1.5 on 2025-02-13 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActiveStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(max_length=255)),
                ("class_name", models.CharField(max_length=20)),
                ("description", models.CharField(max_length=550)),
                ("image", models.ImageField(upload_to="active_student_img")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FaceOfSchool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(max_length=225)),
                ("image", models.ImageField(upload_to="face_image")),
                ("description", models.CharField(max_length=550)),
                (
                    "choices",
                    models.CharField(
                        choices=[("TEACHER", "O'qtuvchi"), ("STUDENT", "O'quvchi")],
                        default="TEACHER",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Subjects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(max_length=255)),
                ("position", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="teacher_image")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=550)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="news_image"),
                ),
                (
                    "likes",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="liked_news",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "views",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="view_count",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                ("text", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "new",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_new",
                        to="common.news",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Notifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                ("message", models.CharField(max_length=550)),
                ("link", models.CharField(blank=True, max_length=255, null=True)),
                ("is_sent", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "start_date",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("end_date", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "class_choices",
                    models.CharField(
                        choices=[
                            ("5-CLASS", "5-sinf"),
                            ("6-CLASS", "6-sinf"),
                            ("7-CLASS", "7-sinf"),
                            ("8-CLASS", "8-sinf"),
                            ("9-CLASS", "9-sinf"),
                            ("10-CLASS", "10-sinf"),
                            ("11-CLASS", "11-sinf"),
                        ],
                        default="5-CLASS",
                        max_length=10,
                    ),
                ),
                (
                    "subjects",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_objects",
                        to="common.subjects",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Questions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                ("question_text", models.TextField()),
                (
                    "true_answer",
                    models.CharField(
                        choices=[("A", "a"), ("B", "b"), ("C", "c"), ("D", "d")],
                        default="A",
                        max_length=2,
                    ),
                ),
                ("variant_a", models.CharField(max_length=255)),
                ("variant_b", models.CharField(max_length=255)),
                ("variant_c", models.CharField(max_length=255)),
                ("variant_d", models.CharField(max_length=255)),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_test",
                        to="common.test",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
