# Generated by Django 5.1.5 on 2025-02-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FonImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="fon_images")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="activestudent",
            name="description",
            field=models.TextField(),
        ),
    ]
