# Generated by Django 5.1.5 on 2025-03-15 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_fonimage_alter_activestudent_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notifications",
            name="user",
        ),
        migrations.RemoveField(
            model_name="questions",
            name="test",
        ),
        migrations.RemoveField(
            model_name="test",
            name="subjects",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="Notifications",
        ),
        migrations.DeleteModel(
            name="Questions",
        ),
        migrations.DeleteModel(
            name="Test",
        ),
    ]
